#!/bin/zsh
# Xcode Cloud runs this after cloning and before resolving packages (readiness M5, ADR-0013).
#
# The Xcode project is generated by XcodeGen and never committed (ADR-0002), so it is generated here,
# with the pinned XcodeGen checked against its checksum, as in .github/workflows/ci.yml. The Team ID
# comes from Xcode Cloud (CI_TEAM_ID) into the git-ignored Config/Team.xcconfig and is never committed
# (ADR-0015, AGENTS.md rule 5).
set -euo pipefail

XCODEGEN_VERSION="2.46.0"
XCODEGEN_SHA256="4d9e34b62172d645eed6457cac13fc222569974098ef4ee9c3368bedf0196806"

cd "${CI_PRIMARY_REPOSITORY_PATH:?CI_PRIMARY_REPOSITORY_PATH is not set; this script runs in Xcode Cloud}"

tools="$(mktemp -d)"
curl --fail --silent --show-error --location --output "$tools/xcodegen.zip" \
  "https://github.com/yonaskolb/XcodeGen/releases/download/${XCODEGEN_VERSION}/xcodegen.zip"
echo "${XCODEGEN_SHA256}  $tools/xcodegen.zip" | shasum -a 256 -c -
unzip -q "$tools/xcodegen.zip" -d "$tools"

if [ -n "${CI_TEAM_ID:-}" ]; then
  print "DEVELOPMENT_TEAM = ${CI_TEAM_ID}" > Config/Team.xcconfig
fi

"$tools/xcodegen/bin/xcodegen" generate
python3 scripts/ci/write_testplan.py
