#!/usr/bin/env python3
"""Generate the DesignSystem Swift tokens from design/tokens.json (docs/design-system.md). Standard library only.

    python3 scripts/design/generate_tokens.py           # write the generated file
    python3 scripts/design/generate_tokens.py --check   # CI: fail if the file is stale or a rule is broken

Rules checked on every run:
  * each brand colour has all four appearances (light, dark, and each with Increase Contrast);
  * every declared contrast pair meets its minimum WCAG 2.2 ratio in every appearance;
  * spacing tokens are multiples of 4 (the 8-point grid with 4-point half-steps).
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TOKENS = ROOT / "design" / "tokens.json"
OUTPUT = ROOT / "Packages" / "DesignSystem" / "Sources" / "DesignSystem" / "Generated" / "Tokens.swift"
APPEARANCES = ("light", "dark", "lightHighContrast", "darkHighContrast")
EXTENSION = "com.algorythmos.appearances"


def rgb(hex_value: str) -> tuple[float, float, float]:
    value = hex_value.lstrip("#")
    if len(value) != 6:
        raise SystemExit(f"colour {hex_value!r} is not #RRGGBB")
    return tuple(int(value[i:i + 2], 16) / 255 for i in (0, 2, 4))  # type: ignore[return-value]


def luminance(hex_value: str) -> float:
    def channel(c: float) -> float:
        return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4
    r, g, b = (channel(c) for c in rgb(hex_value))
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def contrast(a: str, b: str) -> float:
    la, lb = sorted((luminance(a), luminance(b)), reverse=True)
    return (la + 0.05) / (lb + 0.05)


def lookup(tokens: dict, path: str) -> dict:
    node = tokens
    for part in path.split("."):
        node = node[part]
    return node


def check(tokens: dict) -> list[str]:
    errors = []
    for group in ("brand", "intelligence"):
        for name, token in tokens["color"][group].items():
            values = token.get("$extensions", {}).get(EXTENSION, {})
            missing = [a for a in APPEARANCES if a not in values]
            if missing:
                errors.append(f"color.{group}.{name} lacks {missing}")
    # A system token may override its system colour with explicit values; then it needs all four.
    for name, token in tokens["color"]["system"].items():
        values = token.get("$extensions", {}).get(EXTENSION)
        if values is not None:
            missing = [a for a in APPEARANCES if a not in values]
            if missing:
                errors.append(f"color.system.{name} lacks {missing}")
    for pair in tokens.get("contrastPairs", []):
        fg = lookup(tokens, pair["foreground"])["$extensions"][EXTENSION]
        bg = lookup(tokens, pair["background"])["$extensions"][EXTENSION]
        for appearance in APPEARANCES:
            ratio = contrast(fg[appearance], bg[appearance])
            if ratio < pair["minRatio"]:
                errors.append(f"{pair['foreground']} on {pair['background']} ({appearance}) is {ratio:.2f}:1, below {pair['minRatio']}:1")
    for name, token in tokens["space"].items():
        if token["$value"] % 4:
            errors.append(f"space.{name} = {token['$value']} is not a multiple of 4")
    return errors


def swift_color(values: dict) -> str:
    parts = []
    for appearance in APPEARANCES:
        r, g, b = rgb(values[appearance])
        parts.append(f"{appearance}: RGB({r:.4f}, {g:.4f}, {b:.4f})")
    return ", ".join(parts)


def render(tokens: dict) -> str:
    lines = [
        "// swift-format-ignore-file",
        "// Generated by scripts/design/generate_tokens.py from design/tokens.json. Do not edit by hand.",
        "import SwiftUI",
        "",
        "/// Colour tokens (docs/design-system.md). Brand tokens resolve per appearance, including Increase Contrast.",
        "public struct DesignColors: Sendable {",
    ]
    for group in ("brand", "intelligence"):
        for name, token in tokens["color"][group].items():
            values = token["$extensions"][EXTENSION]
            swift_name = f"{group}{name[0].upper()}{name[1:]}"
            summary = ", ".join(f"{a} {values[a]}" for a in APPEARANCES)
            lines += [f"  /// `color.{group}.{name}`: {summary}.",
                      f"  public var {swift_name}: Color {{ DynamicColor.make({swift_color(values)}) }}"]
    for name, token in tokens["color"]["system"].items():
        values = token.get("$extensions", {}).get(EXTENSION)
        if values is not None:
            summary = ", ".join(f"{a} {values[a]}" for a in APPEARANCES)
            lines += [f"  /// `color.system.{name}`: {summary} (replaces `{token['$value']}` for 4.5:1 text contrast).",
                      f"  public var {name}: Color {{ DynamicColor.make({swift_color(values)}) }}"]
            continue
        lines += [f"  /// Resolves to the system colour `{token['$value']}`.",
                  f"  public var {name}: Color {{ DynamicColor.system(.{token['$value']}) }}"]
    lines += ["}", "", "/// Spacing tokens: an 8-point grid with 4-point half-steps.", "public enum Spacing {"]
    for name, token in tokens["space"].items():
        lines += [f"  /// `space.{name}` = {token['$value']} points.", f"  public static let {name}: CGFloat = {token['$value']}"]
    lines += ["}", "", "/// Size tokens.", "public enum Sizes {"]
    for name, token in tokens["size"].items():
        lines += [f"  /// `size.{name}` = {token['$value']} points.", f"  public static let {name}: CGFloat = {token['$value']}"]
    lines += ["}", ""]
    return "\n".join(lines)


def main() -> int:
    tokens = json.loads(TOKENS.read_text(encoding="utf-8"))
    errors = check(tokens)
    for e in errors:
        print(f"::error::{e}")
    rendered = render(tokens)
    if "--check" in sys.argv:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            print("::error::Packages/DesignSystem Generated/Tokens.swift is stale; run scripts/design/generate_tokens.py")
            errors.append("stale")
    elif not errors:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"design tokens: {len(errors)} problem(s)")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
